import type { SlideConfig } from '@/types/deck'

export const slides: SlideConfig[] = [
  {
    id: 'cover',
    type: 'cover',
    section: 'opening',
    title: 'AI Coding 不只是写代码',
    subtitle: '把零散的小技巧整理成一个可复用的小流程',
  },
  {
    id: 'hook-shared-topic',
    type: 'workflow',
    section: 'opening',
    eyebrow: '开场',
    title: '很多 AI Coding 经验，其实都在讲同一件事',
    subtitle: '让 AI 更清楚任务、理解上下文，并交付更方便继续使用的结果。',
    steps: ['Prompt', 'Context', 'Plan', 'Rules', 'Checklist', 'Output', 'Automation'],
    statement: '这次分享，就是把这些零散点串起来。',
  },
  {
    id: 'agenda',
    type: 'agenda',
    section: 'opening',
    eyebrow: '目录',
    title: '今天整理 5 个小细节',
    cards: [
      { title: '把 Prompt 写得像任务' },
      { title: '先整理计划，再进入执行' },
      { title: '给 AI 固定的项目说明入口' },
      { title: '从小流程开始做自动化' },
      { title: '让 AI 交付结构化结果' },
      { title: 'Demo', description: '活动入口入版任务包生成器' },
    ],
  },
  {
    id: 'chapter-prompt',
    type: 'cover',
    section: 'prompt',
    eyebrow: '01',
    title: '把 Prompt 写得像任务',
    subtitle: '不是多写字，而是把关键信息放进去。',
  },
  {
    id: 'prompt-context',
    type: 'compare',
    section: 'prompt',
    eyebrow: '一句话需求，通常缺少上下文',
    title: '不要只说“帮我整理一下这个功能”',
    left: {
      label: '一句话',
      title: '帮我整理一下这个功能。',
      content: 'AI 不知道为什么要做、最终要得到什么、参考哪些材料、输出应该长什么样。',
      tone: 'muted',
    },
    right: {
      label: '任务式',
      title: '把关键信息拆出来',
      content: '背景、目标、输入、输出、检查，让结果更接近可继续处理的材料。',
      tone: 'accent',
    },
  },
  {
    id: 'prompt-fields',
    type: 'method',
    section: 'prompt',
    eyebrow: '任务字段',
    title: '把任务拆成 6 个固定字段',
    steps: ['背景', '目标', '输入', '范围', '输出', '检查'],
    statement: '输出决定结果能不能继续使用，检查帮助 AI 补一遍完成标准。',
  },
  {
    id: 'chapter-plan',
    type: 'cover',
    section: 'plan',
    eyebrow: '02',
    title: '先整理计划，再进入执行',
    subtitle: '复杂任务先对齐理解，后面会少改很多轮。',
  },
  {
    id: 'plan-before-execute',
    type: 'method',
    section: 'plan',
    eyebrow: '计划阶段',
    title: '先让 AI 说说它准备怎么做',
    steps: ['复述理解', '拆分步骤', '列出材料', '说明输出', '给出待补充信息'],
    statement: '先看它有没有理解偏，再决定要不要继续执行。',
  },
  {
    id: 'plan-prompt-starter',
    type: 'summary',
    section: 'plan',
    eyebrow: '好用的一句话',
    title: '这句话很适合放在任务开头',
    quote: '先不要直接执行。请先复述你的理解，列出处理步骤，再说明需要我补充什么。',
    cards: [
      { title: '需求整理' },
      { title: '代码修改' },
      { title: '文档生成' },
      { title: 'Checklist 生成' },
    ],
  },
  {
    id: 'chapter-rules',
    type: 'cover',
    section: 'rules',
    eyebrow: '03',
    title: '给 AI 固定的项目说明入口',
    subtitle: '长期规则不要每次都靠临时聊天补充。',
  },
  {
    id: 'rules-long-term',
    type: 'case',
    section: 'rules',
    eyebrow: '项目习惯',
    title: '有些项目习惯，应该写成长期说明',
    cards: [
      { title: '目录结构' },
      { title: '常用命令' },
      { title: '命名规则' },
      { title: '代码风格' },
      { title: '提交格式' },
      { title: '检查方式' },
    ],
  },
  {
    id: 'rules-entry',
    type: 'case',
    section: 'rules',
    eyebrow: '说明入口',
    title: '项目说明入口可以写什么',
    cards: [
      { title: '项目怎么启动' },
      { title: '目录怎么分层' },
      { title: '文件怎么命名' },
      { title: '常用命令有哪些' },
      { title: '提交说明怎么写' },
      { title: '结果应该怎么检查' },
    ],
    statement: '这份说明不需要一开始就完整，可以随着重复问题慢慢沉淀。',
  },
  {
    id: 'chapter-automation',
    type: 'cover',
    section: 'automation',
    eyebrow: '04',
    title: '从小流程开始做自动化',
    subtitle: '先找重复、清晰、容易模板化的环节。',
  },
  {
    id: 'automation-small-tasks',
    type: 'case',
    section: 'automation',
    eyebrow: '整理类任务',
    title: '适合先交给 AI 的，往往是整理类任务',
    cards: [
      { title: '需求拆解' },
      { title: '材料清单' },
      { title: '任务说明' },
      { title: '检查清单' },
      { title: '变更摘要' },
      { title: '提交说明' },
    ],
  },
  {
    id: 'automation-prompt-template',
    type: 'case',
    section: 'automation',
    eyebrow: '模板化',
    title: '好用的 Prompt，值得保存成模板',
    cards: [
      { title: '输入材料' },
      { title: '处理步骤' },
      { title: '输出格式' },
      { title: '检查清单' },
      { title: '下一步建议' },
    ],
    statement: '下次遇到类似任务，替换输入材料，就能复用同一套处理方式。',
  },
  {
    id: 'chapter-output',
    type: 'cover',
    section: 'output',
    eyebrow: '05',
    title: '让 AI 交付结构化结果',
    subtitle: '输出越结构化，越容易进入下一步。',
  },
  {
    id: 'output-format',
    type: 'case',
    section: 'output',
    eyebrow: '输出格式',
    title: '提前规定格式，会少很多整理时间',
    cards: [
      { title: '材料清单', description: '用表格列材料' },
      { title: '检查项', description: '用 Checklist 列验收点' },
      { title: '任务包', description: '用 Markdown 写结构' },
      { title: '交互流程', description: '用步骤说明动作' },
      { title: '变更摘要', description: '用摘要说明本次变化' },
    ],
  },
  {
    id: 'output-next-materials',
    type: 'case',
    section: 'output',
    eyebrow: '下一步',
    title: '不要只要结果，也要下一步材料',
    cards: [
      { title: '还缺什么材料' },
      { title: '下一步怎么处理' },
      { title: '可以继续生成什么' },
      { title: '哪些内容需要补充' },
      { title: '最终结果怎么交接' },
    ],
  },
  {
    id: 'demo-cover',
    type: 'cover',
    section: 'demo',
    eyebrow: 'Demo',
    title: '活动入口入版任务包生成器',
    subtitle: '用一个 Unity UI 入版场景，把前面的几个小细节串起来。',
  },
  {
    id: 'demo-input',
    type: 'compare',
    section: 'demo',
    eyebrow: '输入',
    title: '一段活动入口入版需求',
    left: {
      label: '原始需求',
      title: '新增限时活动入口',
      content: '替换入口 Banner，增加倒计时展示和红点状态，点击跳转活动详情页，活动结束后隐藏入口。',
      tone: 'muted',
    },
    right: {
      label: '字段提取',
      title: '模块 / 资源 / 交互 / 状态 / 检查',
      content: '入口面板、Banner、按钮图标、倒计时文案、跳转目标、未开启/进行中/即将结束/已结束、多语言和窄屏适配。',
      tone: 'accent',
    },
  },
  {
    id: 'demo-output',
    type: 'case',
    section: 'demo',
    eyebrow: '输出',
    title: '一份更容易推进的任务包',
    cards: [
      { title: 'AI 可执行工单' },
      { title: '资源清单' },
      { title: 'UI 状态表' },
      { title: '交互说明' },
      { title: '检查 Checklist' },
      { title: '待补充信息' },
      { title: '提交说明草稿' },
    ],
  },
  {
    id: 'demo-linkback',
    type: 'method',
    section: 'demo',
    eyebrow: '串联',
    title: '这个示例用到了前面 5 个小细节',
    steps: ['任务化 Prompt', '先整理计划', '项目说明入口', '小流程自动化', '结构化输出'],
    statement: '不一定一开始做很大的系统，先把小细节串起来，就能让 AI 更容易进入日常工作。',
  },
  {
    id: 'summary',
    type: 'summary',
    section: 'summary',
    eyebrow: '总结',
    title: '这些小细节，最终是为了让 AI 更容易接住流程',
    quote: 'AI Coding 不只是写代码，也可以帮我们整理任务、沉淀规则、生成清单和推动下一步。',
    cards: [
      { title: '任务写清楚' },
      { title: '上下文给固定' },
      { title: '执行前先整理' },
      { title: '流程从小处开始' },
      { title: '结果结构化输出' },
    ],
  },
  {
    id: 'thanks',
    type: 'qa',
    section: 'ending',
    title: '谢谢',
    subtitle: '欢迎交流：还有哪些重复整理工作，可以先让 AI 接住？',
    cards: [{ title: 'Q&A' }],
  },
]
