import type { SlideConfig } from '@/types/deck'

export const slides: SlideConfig[] = [
  {
    id: 'cover',
    type: 'cover',
    section: 'opening',
    title: 'AI Coding 不只是写代码',
    subtitle: '5 个容易忽略、但能明显改善协作体验的小知识',
  },
  {
    id: 'opening-position',
    type: 'compare',
    section: 'opening',
    title: '这次不聊“神奇提示词”',
    subtitle: '比起寻找一句万能指令，更值得掌握的是怎样交代一件事。',
    left: {
      label: '容易失效',
      title: '临时想到什么就问什么',
      content: '问题说得很短，背景又藏在脑子里。AI 只能按字面补全，很容易把对象、范围或重点理解错。',
      tone: 'muted',
    },
    right: {
      label: '更稳定',
      title: '把任务说成一个小流程',
      content: '先说明为什么做、给谁用，再补充参考内容和边界。信息之间有关系，AI 才能做出靠谱判断。',
      tone: 'accent',
    },
  },
  {
    id: 'hook-shared-topic',
    type: 'workflow',
    section: 'opening',
    title: '很多 AI Coding 经验，其实都在讲同一件事',
    subtitle: '让 AI 少猜一点，多按你的上下文做事。',
    steps: [
      { label: 'Prompt', caption: '提示词' },
      { label: 'Context', caption: '上下文' },
      { label: 'Plan', caption: '计划' },
      { label: 'Rules', caption: '规则' },
      { label: 'Checklist', caption: '检查项' },
      { label: 'Output', caption: '输出' },
      { label: 'Reuse', caption: '复用' },
    ],
    statement: '这些词看起来各讲一块，实际组成的是同一条工作路径。',
  },
  {
    id: 'agenda',
    type: 'agenda',
    section: 'opening',
    title: '今天整理 5 个小知识',
    subtitle: '每个解决一种常见问题，最后用一个 Demo 串起来。',
    cards: [
      { title: '把 Prompt 写得像任务', description: '解决“AI 不知道我到底要什么”。' },
      { title: '先看计划，再开始执行', description: '解决“做了很多，方向却不对”。' },
      { title: '给项目固定说明入口', description: '解决“每次都要从头介绍项目”。' },
      { title: '从小流程开始自动化', description: '解决“同类操作一直手动重做”。' },
      { title: '约定结果的交付格式', description: '解决“内容有了，还得重新加工”。' },
      { title: 'Demo 串一下', description: '看一段原始需求怎样变成可执行资料。' },
    ],
  },
  {
    id: 'chapter-prompt',
    type: 'cover',
    section: 'prompt',
    eyebrow: '01',
    title: '把 Prompt 写得像任务',
    subtitle: '给 AI 一张信息完整的小工单，而不是一句模糊口令。',
    image: '/images/ai-share/prompt-task.png',
    imageAlt: '任务信息、代码与检查项组成的 Prompt 结构示意',
  },
  {
    id: 'prompt-context',
    type: 'compare',
    section: 'prompt',
    title: '不要只说“帮我整理一下这个功能”',
    subtitle: '先找出这句话里没有说出口的信息。',
    left: {
      label: '一句话提问',
      title: '帮我整理一下这个功能。',
      content: '谁会使用、为什么要做、参考什么、做到哪一步，这些决定方向的信息都没有出现。',
      tone: 'muted',
    },
    right: {
      label: '任务式提问',
      title: '把关键信息拆出来',
      content: '把脑中的判断条件摆到桌面上。它不一定更长，但别人接到这段话也能理解你要做什么。',
      tone: 'accent',
    },
  },
  {
    id: 'prompt-fields',
    type: 'method',
    section: 'prompt',
    title: '一个好用的 Prompt，可以固定成 6 个字段',
    subtitle: '每次不用从零想，只要把空位填上。',
    steps: ['背景', '目标', '输入', '范围', '输出', '检查'],
    statement: '字段不是固定话术，它只是提醒你别把关键条件留在脑子里。',
  },
  {
    id: 'chapter-plan',
    type: 'cover',
    section: 'plan',
    eyebrow: '02',
    title: '先整理计划，再进入执行',
    subtitle: '先确认路线，再把时间花在真正的执行上。',
    image: '/images/ai-share/plan-first.png',
    imageAlt: '从需求到验证的分步计划示意',
  },
  {
    id: 'plan-before-execute',
    type: 'method',
    section: 'plan',
    title: '先让 AI 说说它准备怎么做',
    subtitle: '计划本身就是一次成本很低的方向校对。',
    steps: ['复述理解', '拆分步骤', '列出材料', '说明输出', '标出风险', '等待确认'],
    statement: '发现理解偏差时，只需改几行计划；等代码或文档完成后再改，代价就高多了。',
  },
  {
    id: 'plan-prompt-starter',
    type: 'summary',
    section: 'plan',
    title: '这句话很适合放在复杂任务开头',
    quote: '先不要直接执行。请先复述你的理解，列出处理步骤，再说明需要我补充什么。',
    cards: [
      { title: '需求梳理', description: '寻找信息缺口。' },
      { title: '代码修改', description: '估算影响范围。' },
      { title: '文档生成', description: '确定读者和结构。' },
      { title: 'Checklist 生成', description: '定义通过标准。' },
    ],
  },
  {
    id: 'chapter-rules',
    type: 'cover',
    section: 'rules',
    eyebrow: '03',
    title: '给 AI 固定的项目说明入口',
    subtitle: '把目录、命令、习惯和边界写成一页项目使用说明。',
    image: '/images/ai-share/project-rules.png',
    imageAlt: '项目目录、规则与代码模块关系示意',
  },
  {
    id: 'rules-entry',
    type: 'case',
    section: 'rules',
    title: '项目说明入口可以写什么',
    subtitle: '先覆盖最容易产生误解的部分，再随着使用逐步补充。',
    cards: [
      { tag: 'Start', title: '项目怎么启动', description: '开发命令、构建命令、预览方式、常见端口。' },
      { tag: 'Path', title: '目录怎么分层', description: '页面、组件、样式、数据、工具脚本分别放在哪里。' },
      { tag: 'Style', title: '代码风格', description: '命名习惯、组件拆法、注释习惯、哪些写法不要用。' },
      { tag: 'Check', title: '怎么验证结果', description: '跑哪些命令，看哪些页面，检查哪些边界情况。' },
    ],
    statement: '它相当于项目的快速入门页，新成员和 AI 都能从同一个入口建立基础认知。',
  },
  {
    id: 'chapter-automation',
    type: 'cover',
    section: 'automation',
    eyebrow: '04',
    title: '从小流程开始做自动化',
    subtitle: '优先选择步骤稳定、输入明确、结果容易核对的环节。',
    image: '/images/ai-share/small-automation.png',
    imageAlt: '小型自动化流程从输入到检查输出的示意',
  },
  {
    id: 'automation-small-tasks',
    type: 'case',
    section: 'automation',
    title: '先从边界清楚的小任务入手',
    subtitle: '它们技术风险不高，却能省下大量机械操作。',
    cards: [
      { tag: 'Input', title: '需求拆解', description: '把一段描述拆成模块、状态、资源、交互和待确认点。' },
      { tag: 'List', title: '材料清单', description: '把截图、文档、资源、脚本入口整理成可检查列表。' },
      { tag: 'Task', title: '任务说明', description: '把零散信息整理成别人能接手的一页任务包。' },
      { tag: 'Check', title: '检查清单', description: '把容易漏的点变成逐项勾选，而不是靠临场记忆。' },
    ],
    statement: '先把一个步骤做成模板，稳定后再连接前后环节，比一开始设计大系统更容易落地。',
  },
  {
    id: 'chapter-output',
    type: 'cover',
    section: 'output',
    eyebrow: '05',
    title: '让 AI 按约定格式交付',
    subtitle: '同样的内容，呈现方式不同，后续使用成本会差很多。',
    image: '/images/ai-share/structured-output.png',
    imageAlt: '零散内容整理为表格、清单和文档的示意',
  },
  {
    id: 'output-format',
    type: 'case',
    section: 'output',
    title: '先指定结果长什么样',
    subtitle: '表格、清单和分段文档，分别适合不同的使用场景。',
    cards: [
      { tag: 'Table', title: '材料清单', description: '用表格列资源、来源、状态、缺失项。' },
      { tag: 'Todo', title: '检查项', description: '用 Checklist 写验收点，方便逐条确认。' },
      { tag: 'Doc', title: '任务包', description: '用 Markdown 分背景、目标、步骤、风险和输出。' },
      { tag: 'Open', title: '待确认项', description: '把缺失信息和未决问题单独列出，避免混在正文中。' },
    ],
  },
  {
    id: 'demo-cover',
    type: 'cover',
    section: 'demo',
    title: 'Demo：把活动入口需求变成可执行资料',
    subtitle: '看一次从原始描述到交付清单的完整转化。',
    image: '/images/ai-share/demo-entry-ui.png',
    imageAlt: '',
  },
  {
    id: 'demo-input',
    type: 'compare',
    section: 'demo',
    title: '先把原始描述拆成五类信息',
    subtitle: '不润色需求，只补齐实施时需要判断的内容。',
    left: {
      label: '原始描述',
      title: '新增限时活动入口',
      content: '替换入口 Banner，增加倒计时展示和红点状态，点击跳转活动详情页，活动结束后隐藏入口。',
      tone: 'muted',
    },
    right: {
      label: '拆解结果',
      title: '模块 / 资源 / 交互 / 状态 / 检查',
      content: '入口面板、Banner 图、按钮图标、倒计时文案、跳转目标、未开启/进行中/即将结束/已结束、多语言和窄屏适配。',
      tone: 'accent',
    },
  },
  {
    id: 'demo-output',
    type: 'case',
    section: 'demo',
    title: '最后产出 6 份可以直接使用的资料',
    subtitle: '不同角色拿走自己需要的部分，不必再从一段长文里找信息。',
    cards: [
      { title: 'AI 可执行工单', description: '背景、目标、范围、限制和输出格式。' },
      { title: '资源清单', description: '图片、Prefab、文案、多语言、跳转入口。' },
      { title: 'UI 状态表', description: '未开启、进行中、即将结束、已结束等状态。' },
      { title: '交互说明', description: '点击、跳转、红点、倒计时、隐藏逻辑。' },
      { title: '检查 Checklist', description: '资源、适配、文案、状态、交互逐项确认。' },
      { title: '待补充信息', description: '把当前还不明确的问题单独列出来。' },
    ],
  },
  {
    id: 'thanks',
    type: 'qa',
    section: 'ending',
    title: '谢谢',
    subtitle: '以上就是这次分享的全部内容。',
  },
]
