import type { SlideConfig } from '@/types/deck'

export const slides: SlideConfig[] = [
  {
    id: 'cover',
    type: 'cover',
    section: 'opening',
    eyebrow: 'AI 分享会',
    title: 'AI 不是工具，是新的工作方式',
    subtitle: '从“会用工具”到“会设计工作流”',
  },
  {
    id: 'hook-time-compression',
    type: 'hook',
    section: 'opening',
    eyebrow: '开场钩子',
    title: '3 分钟完成原本 1 小时的工作',
    subtitle: '真正的变化不是多了一个聊天框，而是工作流程被重新压缩。',
    metric: {
      from: '60 min',
      to: '3 min',
      label: '资料整理 + 大纲生成 + 初稿改写',
    },
  },
  {
    id: 'question-why-no-efficiency',
    type: 'question',
    section: 'opening',
    eyebrow: '反常识问题',
    title: '为什么很多人用了 AI，效率反而没有提升？',
    subtitle: '因为他们只是把 AI 当搜索引擎，而不是协作对象。',
  },
  {
    id: 'agenda',
    type: 'agenda',
    section: 'opening',
    eyebrow: '今天只讲三件事',
    title: '从会提问，到会搭工作流',
    cards: [
      { title: 'AI 能做什么', description: '识别适合交给 AI 的重复脑力劳动' },
      { title: '怎么让 AI 做好', description: '用角色、背景、标准和格式定义任务' },
      { title: '如何落地到工作', description: '把单次提问升级为稳定工作流' },
    ],
  },
  {
    id: 'compare-prompt',
    type: 'compare',
    section: 'method',
    eyebrow: '提问方式决定输出质量',
    title: '普通提问 vs 高质量提问',
    left: {
      label: '普通提问',
      title: '帮我写一个活动文案',
      content: '问题太短，缺少角色、场景、受众、目标和输出格式。',
      tone: 'muted',
    },
    right: {
      label: '高质量提问',
      title: '你是资深电商运营，请根据产品信息写一份微信群转化文案',
      content: '要求突出限时优惠、稀缺感和行动按钮，并输出 3 个不同版本。',
      tone: 'accent',
    },
  },
  {
    id: 'method-five-parts',
    type: 'method',
    section: 'method',
    eyebrow: 'Prompt 不是咒语，是任务说明书',
    title: '一个好任务，需要五个组成部分',
    steps: ['角色', '任务', '背景', '标准', '格式'],
    statement: '你描述得越像真实任务，AI 的输出越接近可用结果。',
  },
  {
    id: 'workflow-human-ai',
    type: 'workflow',
    section: 'workflow',
    eyebrow: '推荐工作流',
    title: '人负责判断，AI 负责生成和整理',
    steps: ['输入资料', 'AI 生成初稿', '人判断方向', 'AI 修订细节', '输出结果'],
  },
  {
    id: 'case-customer-service',
    type: 'case',
    section: 'case',
    eyebrow: '案例 1',
    title: '客服问答：从人工翻资料到自动匹配答案',
    cards: [
      { title: '过去', description: '客服在聊天窗口和文档之间来回搜索。' },
      { title: '现在', description: 'AI 先理解问题，再从知识库里匹配候选答案。' },
      { title: '人负责', description: '确认语气、价格、政策是否准确。' },
    ],
  },
  {
    id: 'case-code-review',
    type: 'case',
    section: 'case',
    eyebrow: '案例 2',
    title: '代码审查：不要只看提交信息，要看具体代码变化',
    cards: [
      { title: '看结构', description: '模块边界是否清楚，职责是否拆分。' },
      { title: '看实现', description: '状态、事件、数据流是否有隐藏耦合。' },
      { title: '看风险', description: '是否引入回归、性能问题或维护成本。' },
    ],
  },
  {
    id: 'risk-boundary',
    type: 'risk',
    section: 'risk',
    eyebrow: '边界意识',
    title: 'AI 可以加速，但不能替你负责',
    cards: [
      { title: '幻觉', description: '看起来合理，不代表真实。' },
      { title: '隐私', description: '敏感资料不能随便丢给模型。' },
      { title: '版权', description: '生成内容仍然需要检查来源和使用场景。' },
      { title: '依赖', description: '最终判断必须留在人手里。' },
    ],
  },
  {
    id: 'summary',
    type: 'summary',
    section: 'summary',
    eyebrow: '总结',
    title: '会用 AI 的人，不是少工作，而是更快完成判断',
    quote: '把 AI 当助手，只能省一点时间；把 AI 放进工作流，才会真正改变效率。',
    cards: [
      { title: '从低风险任务开始' },
      { title: '把好问题模板化' },
      { title: '让流程可复用' },
    ],
  },
  {
    id: 'qa',
    type: 'qa',
    section: 'ending',
    title: 'Q&A',
    subtitle: '欢迎提问，也可以现场拿一个工作任务一起改造成 AI 工作流。',
  },
]
